FROM node:19-alpine
RUN apk update && apk add git

RUN mkdir /app
WORKDIR /app
# COPY package*.json /app

# # install latest npm and clean cache
# RUN npm install --location=global npm@8.11.0


# # RUN npm i --silent
# # RUN npm cache clean --force
# RUN npm i --location=global react-scripts@5.0.1

# COPY . /app

# copy package.json
COPY package.json ./

# copy package-lock.json
COPY package-lock.json ./

# CMD ["npm", "start"]

RUN npm install --legacy-peer-deps
EXPOSE 3000
CMD ["npm", "start"]
